#!/bin/bash

# check if we are on openmamba
if [ ! -f /etc/fedora-release ]; then
    echo "This script is only for fedora"
    exit
fi

# check if we are root
if [ "$EUID" -eq 0 ]; then
  echo "Please run as normal user"
  exit
fi
echo "Download sources..."
spectool -g -R penguins-eggs.spec
echo "Building package..."
/usr/bin/rpmbuild -ba ./penguins-eggs.spec
