#!/bin/bash

# check if we are on openmamba
if [ ! -f /etc/openmamba-release ]; then
    echo "This script is only for openmamba"
    exit
fi

# check if we are root
if [ "$EUID" -eq 0 ]; then
  echo "Please run as normal user"
  exit
fi

clear
echo "_topdir: " $(rpm --eval '%_topdir')
echo "__sourcedir: " $(rpm --eval '%_sourcedir')
echo "_download_cmd: " $(rpm --eval '%_download_cmd')
echo ""
rpmbuild -bs ./penguins-eggs.spec
rpmbuild  -bb ./penguins-eggs.spec
