#!/bin/bash

# check if we are on openmamba
if [ ! -f /etc/openmamba-release ]; then
    echo "This script is only for openmamba"
    exit
fi

# check if we are root
if [ "$EUID" -eq 0 ]; then
  echo "Please run as normal user"
  exit
fi
echo "Building package..."
#/usr/bin/rpmbuild -bb ./penguins-eggs.spec
/usr/bin/rpmbuild  -bb ./penguins-eggs.spec
