#!/bin/bash
mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
echo '%_topdir %(echo $HOME)/rpmbuild' > ~/.rpmmacros
echo '%_download_cmd /usr/bin/wget -O %{O} %{U}' >> ~/.rpmmacros
source ~/.bashrc

