#!/bin/bash

# Script to create a naked rootfs for OpenMamba
# Usage: ./mknaked.sh

wget https://cdn.openmamba.org/pub/openmamba/media/rolling/rootfs/it/openmamba-rootfs-it-snapshot-20250823.x86_64.tar.xz
sudo mkdir naked
sudo mount /dev/sda1 naked
cd naked
sudo tar -xf ../openmamba-rootfs-base-en-snapshot-20250815.x86_64.tar.xz
# dnf install kernel
# depmod -a 6.12.37-1mamba-x86_64
# dracut --force /boot/initramfs-6.12.37-1mamba-x86_64.img 6.12.37-1mamba-x86_64


