#!/bin/bash

# Script to create a naked rootfs for OpenMamba

scp artisan@192.168.1.2:/home/artisan/openmamba-rootfs-base-en-snapshot-20250815.x86_64.tar.xz .

echo "Creating NAKED rootfs for OpenMamba"
echo ""
echo "Step 1: Prepare the environment"
NAKED_HOME='/home/live/naked'
echo "mkdir $NAKED_HOME"
echo "mount /dev/sda1 $NAKED_HOME"
echo "cd $NAKED_HOME"
echo ""
echo "Step 2: Extract the rootfs"
echo "sudo tar -xf ../home/artisan/openmamba-rootfs-base-en-snapshot-20250815.x86_64.tar.xz"

# dnf install kernel
# depmod -a 6.12.37-1mamba-x86_64
# dracut --force /boot/initramfs-6.12.37-1mamba-x86_64.img 6.12.37-1mamba-x86_64


