#!/bin/bash
# mkdir -p ~/naked/{dev/pts,proc,run,sys}

# Esegui i comandi di mount

sudo mount --bind /dev ~/naked/dev
sudo mount --bind /dev/pts ~/naked/dev/pts 
sudo mount --bind /proc ~/naked/proc
sudo mount --bind /run ~/naked/run
sudo mount --bind /sys ~/naked/sys

echo "sudo umount -R $HOME/naked"
sudo chroot ~/naked

