#!/bin/bash

echo "--- Pulizia dei tentativi precedenti... ---"
rm -rf ~/rpmbuild/BUILD/*
rm -rf ~/rpmbuild/BUILDROOT/*
rm -rf ~/rpmbuild/RPMS/*
rm -rf ~/rpmbuild/SRPMS/*
rm -rf ~/rpmbuild/SOURCES/*
echo "--- Avvia la nuova build... ---"
