#!/bin/bash

clear
echo downlad

_bootloadersver=25.11.27

version="25.10.30"
name="penguins-eggs"
RPM_SOURCES_DIR="$HOME/rpmbuild/SOURCES"



Source1="https://github.com/pieroproietti/penguins-bootloaders/releases/download/v$_bootloadersver/bootloaders.tar.gz"
Dest1="bootloaders.tar.gz"

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
echo "Cartella di lavoro: $TEMP_DIR"


# Download del sorgente principale
wget -O "$Dest1" "$Source1"
mv "$Dest1" "$RPM_SOURCES_DIR/"
cd ..
rm -rf "$TEMP_DIR"
ls -l "$RPM_SOURCES_DIR"